//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace PespaSistem {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
    [Serializable()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.ComponentModel.ToolboxItem(true)]
    [System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [System.Xml.Serialization.XmlRootAttribute("DsProdukteTotal")]
    [System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class DsProdukteTotal : System.Data.DataSet {
        
        private PRODUKTE_TOTALDataTable tablePRODUKTE_TOTAL;
        
        private PRODUKT_AKSESOREDataTable tablePRODUKT_AKSESORE;
        
        private System.Data.SchemaSerializationMode _schemaSerializationMode = System.Data.SchemaSerializationMode.IncludeSchema;
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public DsProdukteTotal() {
            this.BeginInit();
            this.InitClass();
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected DsProdukteTotal(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == System.Data.SchemaSerializationMode.IncludeSchema)) {
                System.Data.DataSet ds = new System.Data.DataSet();
                ds.ReadXmlSchema(new System.Xml.XmlTextReader(new System.IO.StringReader(strSchema)));
                if ((ds.Tables["PRODUKTE_TOTAL"] != null)) {
                    base.Tables.Add(new PRODUKTE_TOTALDataTable(ds.Tables["PRODUKTE_TOTAL"]));
                }
                if ((ds.Tables["PRODUKT_AKSESORE"] != null)) {
                    base.Tables.Add(new PRODUKT_AKSESOREDataTable(ds.Tables["PRODUKT_AKSESORE"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new System.Xml.XmlTextReader(new System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.DesignerSerializationVisibility(System.ComponentModel.DesignerSerializationVisibility.Content)]
        public PRODUKTE_TOTALDataTable PRODUKTE_TOTAL {
            get {
                return this.tablePRODUKTE_TOTAL;
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.DesignerSerializationVisibility(System.ComponentModel.DesignerSerializationVisibility.Content)]
        public PRODUKT_AKSESOREDataTable PRODUKT_AKSESORE {
            get {
                return this.tablePRODUKT_AKSESORE;
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.BrowsableAttribute(true)]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override System.Data.DataSet Clone() {
            DsProdukteTotal cln = ((DsProdukteTotal)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void ReadXmlSerializable(System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                System.Data.DataSet ds = new System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["PRODUKTE_TOTAL"] != null)) {
                    base.Tables.Add(new PRODUKTE_TOTALDataTable(ds.Tables["PRODUKTE_TOTAL"]));
                }
                if ((ds.Tables["PRODUKT_AKSESORE"] != null)) {
                    base.Tables.Add(new PRODUKT_AKSESOREDataTable(ds.Tables["PRODUKT_AKSESORE"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            System.IO.MemoryStream stream = new System.IO.MemoryStream();
            this.WriteXmlSchema(new System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return System.Xml.Schema.XmlSchema.Read(new System.Xml.XmlTextReader(stream), null);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars(bool initTable) {
            this.tablePRODUKTE_TOTAL = ((PRODUKTE_TOTALDataTable)(base.Tables["PRODUKTE_TOTAL"]));
            if ((initTable == true)) {
                if ((this.tablePRODUKTE_TOTAL != null)) {
                    this.tablePRODUKTE_TOTAL.InitVars();
                }
            }
            this.tablePRODUKT_AKSESORE = ((PRODUKT_AKSESOREDataTable)(base.Tables["PRODUKT_AKSESORE"]));
            if ((initTable == true)) {
                if ((this.tablePRODUKT_AKSESORE != null)) {
                    this.tablePRODUKT_AKSESORE.InitVars();
                }
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitClass() {
            this.DataSetName = "DsProdukteTotal";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/DsProdukteTotal.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = System.Data.SchemaSerializationMode.IncludeSchema;
            this.tablePRODUKTE_TOTAL = new PRODUKTE_TOTALDataTable();
            base.Tables.Add(this.tablePRODUKTE_TOTAL);
            this.tablePRODUKT_AKSESORE = new PRODUKT_AKSESOREDataTable();
            base.Tables.Add(this.tablePRODUKT_AKSESORE);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private bool ShouldSerializePRODUKTE_TOTAL() {
            return false;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private bool ShouldSerializePRODUKT_AKSESORE() {
            return false;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void SchemaChanged(object sender, System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public static System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(System.Xml.Schema.XmlSchemaSet xs) {
            DsProdukteTotal ds = new DsProdukteTotal();
            System.Xml.Schema.XmlSchemaComplexType type = new System.Xml.Schema.XmlSchemaComplexType();
            System.Xml.Schema.XmlSchemaSequence sequence = new System.Xml.Schema.XmlSchemaSequence();
            xs.Add(ds.GetSchemaSerializable());
            System.Xml.Schema.XmlSchemaAny any = new System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            return type;
        }
        
        public delegate void PRODUKTE_TOTALRowChangeEventHandler(object sender, PRODUKTE_TOTALRowChangeEvent e);
        
        public delegate void PRODUKT_AKSESORERowChangeEventHandler(object sender, PRODUKT_AKSESORERowChangeEvent e);
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        [System.Serializable()]
        [System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class PRODUKTE_TOTALDataTable : System.Data.DataTable, System.Collections.IEnumerable {
            
            private System.Data.DataColumn columnID_PRODUKTI;
            
            private System.Data.DataColumn columnEMER_PRODUKTI;
            
            private System.Data.DataColumn columnID_LLOJ_PRODUKTI;
            
            private System.Data.DataColumn columnLLOJ_PRODUKTI;
            
            private System.Data.DataColumn columnID_LLOJ_SISTEMI;
            
            private System.Data.DataColumn columnLLOJ_SISTEMI;
            
            private System.Data.DataColumn columnEMER_GJATE;
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public PRODUKTE_TOTALDataTable() {
                this.TableName = "PRODUKTE_TOTAL";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal PRODUKTE_TOTALDataTable(System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected PRODUKTE_TOTALDataTable(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn ID_PRODUKTIColumn {
                get {
                    return this.columnID_PRODUKTI;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn EMER_PRODUKTIColumn {
                get {
                    return this.columnEMER_PRODUKTI;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn ID_LLOJ_PRODUKTIColumn {
                get {
                    return this.columnID_LLOJ_PRODUKTI;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn LLOJ_PRODUKTIColumn {
                get {
                    return this.columnLLOJ_PRODUKTI;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn ID_LLOJ_SISTEMIColumn {
                get {
                    return this.columnID_LLOJ_SISTEMI;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn LLOJ_SISTEMIColumn {
                get {
                    return this.columnLLOJ_SISTEMI;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn EMER_GJATEColumn {
                get {
                    return this.columnEMER_GJATE;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public PRODUKTE_TOTALRow this[int index] {
                get {
                    return ((PRODUKTE_TOTALRow)(this.Rows[index]));
                }
            }
            
            public event PRODUKTE_TOTALRowChangeEventHandler PRODUKTE_TOTALRowChanging;
            
            public event PRODUKTE_TOTALRowChangeEventHandler PRODUKTE_TOTALRowChanged;
            
            public event PRODUKTE_TOTALRowChangeEventHandler PRODUKTE_TOTALRowDeleting;
            
            public event PRODUKTE_TOTALRowChangeEventHandler PRODUKTE_TOTALRowDeleted;
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void AddPRODUKTE_TOTALRow(PRODUKTE_TOTALRow row) {
                this.Rows.Add(row);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public PRODUKTE_TOTALRow AddPRODUKTE_TOTALRow(string EMER_PRODUKTI, string LLOJ_PRODUKTI, string LLOJ_SISTEMI, string EMER_GJATE) {
                PRODUKTE_TOTALRow rowPRODUKTE_TOTALRow = ((PRODUKTE_TOTALRow)(this.NewRow()));
                rowPRODUKTE_TOTALRow.ItemArray = new object[] {
                        null,
                        EMER_PRODUKTI,
                        null,
                        LLOJ_PRODUKTI,
                        null,
                        LLOJ_SISTEMI,
                        EMER_GJATE};
                this.Rows.Add(rowPRODUKTE_TOTALRow);
                return rowPRODUKTE_TOTALRow;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public virtual System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public override System.Data.DataTable Clone() {
                PRODUKTE_TOTALDataTable cln = ((PRODUKTE_TOTALDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override System.Data.DataTable CreateInstance() {
                return new PRODUKTE_TOTALDataTable();
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal void InitVars() {
                this.columnID_PRODUKTI = base.Columns["ID_PRODUKTI"];
                this.columnEMER_PRODUKTI = base.Columns["EMER_PRODUKTI"];
                this.columnID_LLOJ_PRODUKTI = base.Columns["ID_LLOJ_PRODUKTI"];
                this.columnLLOJ_PRODUKTI = base.Columns["LLOJ_PRODUKTI"];
                this.columnID_LLOJ_SISTEMI = base.Columns["ID_LLOJ_SISTEMI"];
                this.columnLLOJ_SISTEMI = base.Columns["LLOJ_SISTEMI"];
                this.columnEMER_GJATE = base.Columns["EMER_GJATE"];
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            private void InitClass() {
                this.columnID_PRODUKTI = new System.Data.DataColumn("ID_PRODUKTI", typeof(int), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnID_PRODUKTI);
                this.columnEMER_PRODUKTI = new System.Data.DataColumn("EMER_PRODUKTI", typeof(string), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnEMER_PRODUKTI);
                this.columnID_LLOJ_PRODUKTI = new System.Data.DataColumn("ID_LLOJ_PRODUKTI", typeof(int), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnID_LLOJ_PRODUKTI);
                this.columnLLOJ_PRODUKTI = new System.Data.DataColumn("LLOJ_PRODUKTI", typeof(string), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnLLOJ_PRODUKTI);
                this.columnID_LLOJ_SISTEMI = new System.Data.DataColumn("ID_LLOJ_SISTEMI", typeof(int), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnID_LLOJ_SISTEMI);
                this.columnLLOJ_SISTEMI = new System.Data.DataColumn("LLOJ_SISTEMI", typeof(string), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnLLOJ_SISTEMI);
                this.columnEMER_GJATE = new System.Data.DataColumn("EMER_GJATE", typeof(string), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnEMER_GJATE);
                this.columnID_PRODUKTI.AutoIncrement = true;
                this.columnEMER_PRODUKTI.MaxLength = 50;
                this.columnID_LLOJ_PRODUKTI.AutoIncrement = true;
                this.columnLLOJ_PRODUKTI.MaxLength = 50;
                this.columnID_LLOJ_SISTEMI.AutoIncrement = true;
                this.columnLLOJ_SISTEMI.MaxLength = 50;
                this.columnEMER_GJATE.ReadOnly = true;
                this.columnEMER_GJATE.MaxLength = 255;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public PRODUKTE_TOTALRow NewPRODUKTE_TOTALRow() {
                return ((PRODUKTE_TOTALRow)(this.NewRow()));
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override System.Data.DataRow NewRowFromBuilder(System.Data.DataRowBuilder builder) {
                return new PRODUKTE_TOTALRow(builder);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override System.Type GetRowType() {
                return typeof(PRODUKTE_TOTALRow);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanged(System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.PRODUKTE_TOTALRowChanged != null)) {
                    this.PRODUKTE_TOTALRowChanged(this, new PRODUKTE_TOTALRowChangeEvent(((PRODUKTE_TOTALRow)(e.Row)), e.Action));
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanging(System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.PRODUKTE_TOTALRowChanging != null)) {
                    this.PRODUKTE_TOTALRowChanging(this, new PRODUKTE_TOTALRowChangeEvent(((PRODUKTE_TOTALRow)(e.Row)), e.Action));
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleted(System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.PRODUKTE_TOTALRowDeleted != null)) {
                    this.PRODUKTE_TOTALRowDeleted(this, new PRODUKTE_TOTALRowChangeEvent(((PRODUKTE_TOTALRow)(e.Row)), e.Action));
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleting(System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.PRODUKTE_TOTALRowDeleting != null)) {
                    this.PRODUKTE_TOTALRowDeleting(this, new PRODUKTE_TOTALRowChangeEvent(((PRODUKTE_TOTALRow)(e.Row)), e.Action));
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void RemovePRODUKTE_TOTALRow(PRODUKTE_TOTALRow row) {
                this.Rows.Remove(row);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public static System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(System.Xml.Schema.XmlSchemaSet xs) {
                System.Xml.Schema.XmlSchemaComplexType type = new System.Xml.Schema.XmlSchemaComplexType();
                System.Xml.Schema.XmlSchemaSequence sequence = new System.Xml.Schema.XmlSchemaSequence();
                DsProdukteTotal ds = new DsProdukteTotal();
                xs.Add(ds.GetSchemaSerializable());
                System.Xml.Schema.XmlSchemaAny any1 = new System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                System.Xml.Schema.XmlSchemaAny any2 = new System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                System.Xml.Schema.XmlSchemaAttribute attribute1 = new System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                System.Xml.Schema.XmlSchemaAttribute attribute2 = new System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "PRODUKTE_TOTALDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                return type;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        [System.Serializable()]
        [System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class PRODUKT_AKSESOREDataTable : System.Data.DataTable, System.Collections.IEnumerable {
            
            private System.Data.DataColumn columnID_PRODUKT_AKSESORE;
            
            private System.Data.DataColumn columnID_PRODUKTI;
            
            private System.Data.DataColumn columnID_AKSESORE_ALUMINI;
            
            private System.Data.DataColumn columnID_AKSESORE_XHAMI;
            
            private System.Data.DataColumn columnID_AKSESORE;
            
            private System.Data.DataColumn columnFORMULA;
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public PRODUKT_AKSESOREDataTable() {
                this.TableName = "PRODUKT_AKSESORE";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal PRODUKT_AKSESOREDataTable(System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected PRODUKT_AKSESOREDataTable(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn ID_PRODUKT_AKSESOREColumn {
                get {
                    return this.columnID_PRODUKT_AKSESORE;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn ID_PRODUKTIColumn {
                get {
                    return this.columnID_PRODUKTI;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn ID_AKSESORE_ALUMINIColumn {
                get {
                    return this.columnID_AKSESORE_ALUMINI;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn ID_AKSESORE_XHAMIColumn {
                get {
                    return this.columnID_AKSESORE_XHAMI;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn ID_AKSESOREColumn {
                get {
                    return this.columnID_AKSESORE;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn FORMULAColumn {
                get {
                    return this.columnFORMULA;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public PRODUKT_AKSESORERow this[int index] {
                get {
                    return ((PRODUKT_AKSESORERow)(this.Rows[index]));
                }
            }
            
            public event PRODUKT_AKSESORERowChangeEventHandler PRODUKT_AKSESORERowChanging;
            
            public event PRODUKT_AKSESORERowChangeEventHandler PRODUKT_AKSESORERowChanged;
            
            public event PRODUKT_AKSESORERowChangeEventHandler PRODUKT_AKSESORERowDeleting;
            
            public event PRODUKT_AKSESORERowChangeEventHandler PRODUKT_AKSESORERowDeleted;
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void AddPRODUKT_AKSESORERow(PRODUKT_AKSESORERow row) {
                this.Rows.Add(row);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public PRODUKT_AKSESORERow AddPRODUKT_AKSESORERow(int ID_PRODUKTI, int ID_AKSESORE_ALUMINI, int ID_AKSESORE_XHAMI, int ID_AKSESORE, string FORMULA) {
                PRODUKT_AKSESORERow rowPRODUKT_AKSESORERow = ((PRODUKT_AKSESORERow)(this.NewRow()));
                rowPRODUKT_AKSESORERow.ItemArray = new object[] {
                        null,
                        ID_PRODUKTI,
                        ID_AKSESORE_ALUMINI,
                        ID_AKSESORE_XHAMI,
                        ID_AKSESORE,
                        FORMULA};
                this.Rows.Add(rowPRODUKT_AKSESORERow);
                return rowPRODUKT_AKSESORERow;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public PRODUKT_AKSESORERow FindByID_PRODUKT_AKSESORE(int ID_PRODUKT_AKSESORE) {
                return ((PRODUKT_AKSESORERow)(this.Rows.Find(new object[] {
                            ID_PRODUKT_AKSESORE})));
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public virtual System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public override System.Data.DataTable Clone() {
                PRODUKT_AKSESOREDataTable cln = ((PRODUKT_AKSESOREDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override System.Data.DataTable CreateInstance() {
                return new PRODUKT_AKSESOREDataTable();
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal void InitVars() {
                this.columnID_PRODUKT_AKSESORE = base.Columns["ID_PRODUKT_AKSESORE"];
                this.columnID_PRODUKTI = base.Columns["ID_PRODUKTI"];
                this.columnID_AKSESORE_ALUMINI = base.Columns["ID_AKSESORE_ALUMINI"];
                this.columnID_AKSESORE_XHAMI = base.Columns["ID_AKSESORE_XHAMI"];
                this.columnID_AKSESORE = base.Columns["ID_AKSESORE"];
                this.columnFORMULA = base.Columns["FORMULA"];
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            private void InitClass() {
                this.columnID_PRODUKT_AKSESORE = new System.Data.DataColumn("ID_PRODUKT_AKSESORE", typeof(int), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnID_PRODUKT_AKSESORE);
                this.columnID_PRODUKTI = new System.Data.DataColumn("ID_PRODUKTI", typeof(int), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnID_PRODUKTI);
                this.columnID_AKSESORE_ALUMINI = new System.Data.DataColumn("ID_AKSESORE_ALUMINI", typeof(int), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnID_AKSESORE_ALUMINI);
                this.columnID_AKSESORE_XHAMI = new System.Data.DataColumn("ID_AKSESORE_XHAMI", typeof(int), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnID_AKSESORE_XHAMI);
                this.columnID_AKSESORE = new System.Data.DataColumn("ID_AKSESORE", typeof(int), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnID_AKSESORE);
                this.columnFORMULA = new System.Data.DataColumn("FORMULA", typeof(string), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnFORMULA);
                this.Constraints.Add(new System.Data.UniqueConstraint("Constraint1", new System.Data.DataColumn[] {
                                this.columnID_PRODUKT_AKSESORE}, true));
                this.columnID_PRODUKT_AKSESORE.AutoIncrement = true;
                this.columnID_PRODUKT_AKSESORE.AllowDBNull = false;
                this.columnID_PRODUKT_AKSESORE.Unique = true;
                this.columnFORMULA.MaxLength = 50;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public PRODUKT_AKSESORERow NewPRODUKT_AKSESORERow() {
                return ((PRODUKT_AKSESORERow)(this.NewRow()));
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override System.Data.DataRow NewRowFromBuilder(System.Data.DataRowBuilder builder) {
                return new PRODUKT_AKSESORERow(builder);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override System.Type GetRowType() {
                return typeof(PRODUKT_AKSESORERow);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanged(System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.PRODUKT_AKSESORERowChanged != null)) {
                    this.PRODUKT_AKSESORERowChanged(this, new PRODUKT_AKSESORERowChangeEvent(((PRODUKT_AKSESORERow)(e.Row)), e.Action));
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanging(System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.PRODUKT_AKSESORERowChanging != null)) {
                    this.PRODUKT_AKSESORERowChanging(this, new PRODUKT_AKSESORERowChangeEvent(((PRODUKT_AKSESORERow)(e.Row)), e.Action));
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleted(System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.PRODUKT_AKSESORERowDeleted != null)) {
                    this.PRODUKT_AKSESORERowDeleted(this, new PRODUKT_AKSESORERowChangeEvent(((PRODUKT_AKSESORERow)(e.Row)), e.Action));
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleting(System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.PRODUKT_AKSESORERowDeleting != null)) {
                    this.PRODUKT_AKSESORERowDeleting(this, new PRODUKT_AKSESORERowChangeEvent(((PRODUKT_AKSESORERow)(e.Row)), e.Action));
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void RemovePRODUKT_AKSESORERow(PRODUKT_AKSESORERow row) {
                this.Rows.Remove(row);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public static System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(System.Xml.Schema.XmlSchemaSet xs) {
                System.Xml.Schema.XmlSchemaComplexType type = new System.Xml.Schema.XmlSchemaComplexType();
                System.Xml.Schema.XmlSchemaSequence sequence = new System.Xml.Schema.XmlSchemaSequence();
                DsProdukteTotal ds = new DsProdukteTotal();
                xs.Add(ds.GetSchemaSerializable());
                System.Xml.Schema.XmlSchemaAny any1 = new System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                System.Xml.Schema.XmlSchemaAny any2 = new System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                System.Xml.Schema.XmlSchemaAttribute attribute1 = new System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                System.Xml.Schema.XmlSchemaAttribute attribute2 = new System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "PRODUKT_AKSESOREDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                return type;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public partial class PRODUKTE_TOTALRow : System.Data.DataRow {
            
            private PRODUKTE_TOTALDataTable tablePRODUKTE_TOTAL;
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal PRODUKTE_TOTALRow(System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tablePRODUKTE_TOTAL = ((PRODUKTE_TOTALDataTable)(this.Table));
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int ID_PRODUKTI {
                get {
                    try {
                        return ((int)(this[this.tablePRODUKTE_TOTAL.ID_PRODUKTIColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'ID_PRODUKTI\' in table \'PRODUKTE_TOTAL\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablePRODUKTE_TOTAL.ID_PRODUKTIColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string EMER_PRODUKTI {
                get {
                    try {
                        return ((string)(this[this.tablePRODUKTE_TOTAL.EMER_PRODUKTIColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'EMER_PRODUKTI\' in table \'PRODUKTE_TOTAL\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablePRODUKTE_TOTAL.EMER_PRODUKTIColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int ID_LLOJ_PRODUKTI {
                get {
                    try {
                        return ((int)(this[this.tablePRODUKTE_TOTAL.ID_LLOJ_PRODUKTIColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'ID_LLOJ_PRODUKTI\' in table \'PRODUKTE_TOTAL\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablePRODUKTE_TOTAL.ID_LLOJ_PRODUKTIColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string LLOJ_PRODUKTI {
                get {
                    try {
                        return ((string)(this[this.tablePRODUKTE_TOTAL.LLOJ_PRODUKTIColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'LLOJ_PRODUKTI\' in table \'PRODUKTE_TOTAL\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablePRODUKTE_TOTAL.LLOJ_PRODUKTIColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int ID_LLOJ_SISTEMI {
                get {
                    try {
                        return ((int)(this[this.tablePRODUKTE_TOTAL.ID_LLOJ_SISTEMIColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'ID_LLOJ_SISTEMI\' in table \'PRODUKTE_TOTAL\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablePRODUKTE_TOTAL.ID_LLOJ_SISTEMIColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string LLOJ_SISTEMI {
                get {
                    try {
                        return ((string)(this[this.tablePRODUKTE_TOTAL.LLOJ_SISTEMIColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'LLOJ_SISTEMI\' in table \'PRODUKTE_TOTAL\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablePRODUKTE_TOTAL.LLOJ_SISTEMIColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string EMER_GJATE {
                get {
                    try {
                        return ((string)(this[this.tablePRODUKTE_TOTAL.EMER_GJATEColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'EMER_GJATE\' in table \'PRODUKTE_TOTAL\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablePRODUKTE_TOTAL.EMER_GJATEColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsID_PRODUKTINull() {
                return this.IsNull(this.tablePRODUKTE_TOTAL.ID_PRODUKTIColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetID_PRODUKTINull() {
                this[this.tablePRODUKTE_TOTAL.ID_PRODUKTIColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsEMER_PRODUKTINull() {
                return this.IsNull(this.tablePRODUKTE_TOTAL.EMER_PRODUKTIColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetEMER_PRODUKTINull() {
                this[this.tablePRODUKTE_TOTAL.EMER_PRODUKTIColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsID_LLOJ_PRODUKTINull() {
                return this.IsNull(this.tablePRODUKTE_TOTAL.ID_LLOJ_PRODUKTIColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetID_LLOJ_PRODUKTINull() {
                this[this.tablePRODUKTE_TOTAL.ID_LLOJ_PRODUKTIColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsLLOJ_PRODUKTINull() {
                return this.IsNull(this.tablePRODUKTE_TOTAL.LLOJ_PRODUKTIColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetLLOJ_PRODUKTINull() {
                this[this.tablePRODUKTE_TOTAL.LLOJ_PRODUKTIColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsID_LLOJ_SISTEMINull() {
                return this.IsNull(this.tablePRODUKTE_TOTAL.ID_LLOJ_SISTEMIColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetID_LLOJ_SISTEMINull() {
                this[this.tablePRODUKTE_TOTAL.ID_LLOJ_SISTEMIColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsLLOJ_SISTEMINull() {
                return this.IsNull(this.tablePRODUKTE_TOTAL.LLOJ_SISTEMIColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetLLOJ_SISTEMINull() {
                this[this.tablePRODUKTE_TOTAL.LLOJ_SISTEMIColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsEMER_GJATENull() {
                return this.IsNull(this.tablePRODUKTE_TOTAL.EMER_GJATEColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetEMER_GJATENull() {
                this[this.tablePRODUKTE_TOTAL.EMER_GJATEColumn] = System.Convert.DBNull;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public partial class PRODUKT_AKSESORERow : System.Data.DataRow {
            
            private PRODUKT_AKSESOREDataTable tablePRODUKT_AKSESORE;
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal PRODUKT_AKSESORERow(System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tablePRODUKT_AKSESORE = ((PRODUKT_AKSESOREDataTable)(this.Table));
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int ID_PRODUKT_AKSESORE {
                get {
                    return ((int)(this[this.tablePRODUKT_AKSESORE.ID_PRODUKT_AKSESOREColumn]));
                }
                set {
                    this[this.tablePRODUKT_AKSESORE.ID_PRODUKT_AKSESOREColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int ID_PRODUKTI {
                get {
                    try {
                        return ((int)(this[this.tablePRODUKT_AKSESORE.ID_PRODUKTIColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'ID_PRODUKTI\' in table \'PRODUKT_AKSESORE\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablePRODUKT_AKSESORE.ID_PRODUKTIColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int ID_AKSESORE_ALUMINI {
                get {
                    try {
                        return ((int)(this[this.tablePRODUKT_AKSESORE.ID_AKSESORE_ALUMINIColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'ID_AKSESORE_ALUMINI\' in table \'PRODUKT_AKSESORE\' is DBNull." +
                                "", e);
                    }
                }
                set {
                    this[this.tablePRODUKT_AKSESORE.ID_AKSESORE_ALUMINIColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int ID_AKSESORE_XHAMI {
                get {
                    try {
                        return ((int)(this[this.tablePRODUKT_AKSESORE.ID_AKSESORE_XHAMIColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'ID_AKSESORE_XHAMI\' in table \'PRODUKT_AKSESORE\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablePRODUKT_AKSESORE.ID_AKSESORE_XHAMIColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int ID_AKSESORE {
                get {
                    try {
                        return ((int)(this[this.tablePRODUKT_AKSESORE.ID_AKSESOREColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'ID_AKSESORE\' in table \'PRODUKT_AKSESORE\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablePRODUKT_AKSESORE.ID_AKSESOREColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string FORMULA {
                get {
                    try {
                        return ((string)(this[this.tablePRODUKT_AKSESORE.FORMULAColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'FORMULA\' in table \'PRODUKT_AKSESORE\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablePRODUKT_AKSESORE.FORMULAColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsID_PRODUKTINull() {
                return this.IsNull(this.tablePRODUKT_AKSESORE.ID_PRODUKTIColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetID_PRODUKTINull() {
                this[this.tablePRODUKT_AKSESORE.ID_PRODUKTIColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsID_AKSESORE_ALUMININull() {
                return this.IsNull(this.tablePRODUKT_AKSESORE.ID_AKSESORE_ALUMINIColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetID_AKSESORE_ALUMININull() {
                this[this.tablePRODUKT_AKSESORE.ID_AKSESORE_ALUMINIColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsID_AKSESORE_XHAMINull() {
                return this.IsNull(this.tablePRODUKT_AKSESORE.ID_AKSESORE_XHAMIColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetID_AKSESORE_XHAMINull() {
                this[this.tablePRODUKT_AKSESORE.ID_AKSESORE_XHAMIColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsID_AKSESORENull() {
                return this.IsNull(this.tablePRODUKT_AKSESORE.ID_AKSESOREColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetID_AKSESORENull() {
                this[this.tablePRODUKT_AKSESORE.ID_AKSESOREColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsFORMULANull() {
                return this.IsNull(this.tablePRODUKT_AKSESORE.FORMULAColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetFORMULANull() {
                this[this.tablePRODUKT_AKSESORE.FORMULAColumn] = System.Convert.DBNull;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public class PRODUKTE_TOTALRowChangeEvent : System.EventArgs {
            
            private PRODUKTE_TOTALRow eventRow;
            
            private System.Data.DataRowAction eventAction;
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public PRODUKTE_TOTALRowChangeEvent(PRODUKTE_TOTALRow row, System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public PRODUKTE_TOTALRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public class PRODUKT_AKSESORERowChangeEvent : System.EventArgs {
            
            private PRODUKT_AKSESORERow eventRow;
            
            private System.Data.DataRowAction eventAction;
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public PRODUKT_AKSESORERowChangeEvent(PRODUKT_AKSESORERow row, System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public PRODUKT_AKSESORERow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}
namespace PespaSistem.DsProdukteTotalTableAdapters {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.ComponentModel.ToolboxItem(true)]
    [System.ComponentModel.DataObjectAttribute(true)]
    [System.ComponentModel.DesignerAttribute("Microsoft.VSDesigner.DataSource.Design.TableAdapterDesigner, Microsoft.VSDesigner" +
        ", Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a")]
    [System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")]
    public partial class PRODUKTE_TOTALTableAdapter : System.ComponentModel.Component {
        
        private System.Data.OleDb.OleDbDataAdapter _adapter;
        
        private System.Data.OleDb.OleDbConnection _connection;
        
        private System.Data.OleDb.OleDbCommand[] _commandCollection;
        
        private bool _clearBeforeFill;
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public PRODUKTE_TOTALTableAdapter() {
            this.ClearBeforeFill = true;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private System.Data.OleDb.OleDbDataAdapter Adapter {
            get {
                if ((this._adapter == null)) {
                    this.InitAdapter();
                }
                return this._adapter;
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal System.Data.OleDb.OleDbConnection Connection {
            get {
                if ((this._connection == null)) {
                    this.InitConnection();
                }
                return this._connection;
            }
            set {
                this._connection = value;
                if ((this.Adapter.InsertCommand != null)) {
                    this.Adapter.InsertCommand.Connection = value;
                }
                if ((this.Adapter.DeleteCommand != null)) {
                    this.Adapter.DeleteCommand.Connection = value;
                }
                if ((this.Adapter.UpdateCommand != null)) {
                    this.Adapter.UpdateCommand.Connection = value;
                }
                for (int i = 0; (i < this.CommandCollection.Length); i = (i + 1)) {
                    if ((this.CommandCollection[i] != null)) {
                        ((System.Data.OleDb.OleDbCommand)(this.CommandCollection[i])).Connection = value;
                    }
                }
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected System.Data.OleDb.OleDbCommand[] CommandCollection {
            get {
                if ((this._commandCollection == null)) {
                    this.InitCommandCollection();
                }
                return this._commandCollection;
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool ClearBeforeFill {
            get {
                return this._clearBeforeFill;
            }
            set {
                this._clearBeforeFill = value;
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitAdapter() {
            this._adapter = new System.Data.OleDb.OleDbDataAdapter();
            System.Data.Common.DataTableMapping tableMapping = new System.Data.Common.DataTableMapping();
            tableMapping.SourceTable = "Table";
            tableMapping.DataSetTable = "PRODUKTE_TOTAL";
            tableMapping.ColumnMappings.Add("ID_PRODUKTI", "ID_PRODUKTI");
            tableMapping.ColumnMappings.Add("EMER_PRODUKTI", "EMER_PRODUKTI");
            tableMapping.ColumnMappings.Add("ID_LLOJ_PRODUKTI", "ID_LLOJ_PRODUKTI");
            tableMapping.ColumnMappings.Add("LLOJ_PRODUKTI", "LLOJ_PRODUKTI");
            tableMapping.ColumnMappings.Add("ID_LLOJ_SISTEMI", "ID_LLOJ_SISTEMI");
            tableMapping.ColumnMappings.Add("LLOJ_SISTEMI", "LLOJ_SISTEMI");
            tableMapping.ColumnMappings.Add("EMER_GJATE", "EMER_GJATE");
            this._adapter.TableMappings.Add(tableMapping);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitConnection() {
            this._connection = new System.Data.OleDb.OleDbConnection();
            this._connection.ConnectionString = global::PespaSistem.Properties.Settings.Default.PespaSistemConnectionString;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitCommandCollection() {
            this._commandCollection = new System.Data.OleDb.OleDbCommand[1];
            this._commandCollection[0] = new System.Data.OleDb.OleDbCommand();
            this._commandCollection[0].Connection = this.Connection;
            this._commandCollection[0].CommandText = @"SELECT     PRODUKTE.ID_PRODUKTI, PRODUKTE.EMER_PRODUKTI, LLOJ_PRODUKTI.ID_LLOJ_PRODUKTI, LLOJ_PRODUKTI.LLOJ_PRODUKTI, 
                      LLOJ_SISTEMI.ID_LLOJ_SISTEMI, LLOJ_SISTEMI.LLOJ_SISTEMI, 
                      PRODUKTE.EMER_PRODUKTI + '  ' + LLOJ_SISTEMI.LLOJ_SISTEMI AS EMER_GJATE
FROM         ((PRODUKTE INNER JOIN
                      LLOJ_SISTEMI ON PRODUKTE.ID_LLOJ_SISTEMI = LLOJ_SISTEMI.ID_LLOJ_SISTEMI) INNER JOIN
                      LLOJ_PRODUKTI ON PRODUKTE.LLOJ_PRODUKTI = LLOJ_PRODUKTI.ID_LLOJ_PRODUKTI)
WHERE     (PRODUKTE.ID_PRODUKTI <> ?)";
            this._commandCollection[0].CommandType = System.Data.CommandType.Text;
            this._commandCollection[0].Parameters.Add(new System.Data.OleDb.OleDbParameter("ID_PRODUKTI", System.Data.OleDb.OleDbType.Integer, 0, System.Data.ParameterDirection.Input, ((byte)(0)), ((byte)(0)), "ID_PRODUKTI", System.Data.DataRowVersion.Current, false, null));
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")]
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Fill, true)]
        public virtual int Fill(DsProdukteTotal.PRODUKTE_TOTALDataTable dataTable, int ID_PRODUKTI) {
            this.Adapter.SelectCommand = this.CommandCollection[0];
            this.Adapter.SelectCommand.Parameters[0].Value = ((int)(ID_PRODUKTI));
            if ((this.ClearBeforeFill == true)) {
                dataTable.Clear();
            }
            int returnValue = this.Adapter.Fill(dataTable);
            return returnValue;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")]
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Select, true)]
        public virtual DsProdukteTotal.PRODUKTE_TOTALDataTable GetData(int ID_PRODUKTI) {
            this.Adapter.SelectCommand = this.CommandCollection[0];
            this.Adapter.SelectCommand.Parameters[0].Value = ((int)(ID_PRODUKTI));
            DsProdukteTotal.PRODUKTE_TOTALDataTable dataTable = new DsProdukteTotal.PRODUKTE_TOTALDataTable();
            this.Adapter.Fill(dataTable);
            return dataTable;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.ComponentModel.ToolboxItem(true)]
    [System.ComponentModel.DataObjectAttribute(true)]
    [System.ComponentModel.DesignerAttribute("Microsoft.VSDesigner.DataSource.Design.TableAdapterDesigner, Microsoft.VSDesigner" +
        ", Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a")]
    [System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")]
    public partial class PRODUKT_AKSESORETableAdapter : System.ComponentModel.Component {
        
        private System.Data.OleDb.OleDbDataAdapter _adapter;
        
        private System.Data.OleDb.OleDbConnection _connection;
        
        private System.Data.OleDb.OleDbCommand[] _commandCollection;
        
        private bool _clearBeforeFill;
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public PRODUKT_AKSESORETableAdapter() {
            this.ClearBeforeFill = true;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private System.Data.OleDb.OleDbDataAdapter Adapter {
            get {
                if ((this._adapter == null)) {
                    this.InitAdapter();
                }
                return this._adapter;
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal System.Data.OleDb.OleDbConnection Connection {
            get {
                if ((this._connection == null)) {
                    this.InitConnection();
                }
                return this._connection;
            }
            set {
                this._connection = value;
                if ((this.Adapter.InsertCommand != null)) {
                    this.Adapter.InsertCommand.Connection = value;
                }
                if ((this.Adapter.DeleteCommand != null)) {
                    this.Adapter.DeleteCommand.Connection = value;
                }
                if ((this.Adapter.UpdateCommand != null)) {
                    this.Adapter.UpdateCommand.Connection = value;
                }
                for (int i = 0; (i < this.CommandCollection.Length); i = (i + 1)) {
                    if ((this.CommandCollection[i] != null)) {
                        ((System.Data.OleDb.OleDbCommand)(this.CommandCollection[i])).Connection = value;
                    }
                }
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected System.Data.OleDb.OleDbCommand[] CommandCollection {
            get {
                if ((this._commandCollection == null)) {
                    this.InitCommandCollection();
                }
                return this._commandCollection;
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool ClearBeforeFill {
            get {
                return this._clearBeforeFill;
            }
            set {
                this._clearBeforeFill = value;
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitAdapter() {
            this._adapter = new System.Data.OleDb.OleDbDataAdapter();
            System.Data.Common.DataTableMapping tableMapping = new System.Data.Common.DataTableMapping();
            tableMapping.SourceTable = "Table";
            tableMapping.DataSetTable = "PRODUKT_AKSESORE";
            tableMapping.ColumnMappings.Add("ID_PRODUKT_AKSESORE", "ID_PRODUKT_AKSESORE");
            tableMapping.ColumnMappings.Add("ID_PRODUKTI", "ID_PRODUKTI");
            tableMapping.ColumnMappings.Add("ID_AKSESORE_ALUMINI", "ID_AKSESORE_ALUMINI");
            tableMapping.ColumnMappings.Add("ID_AKSESORE_XHAMI", "ID_AKSESORE_XHAMI");
            tableMapping.ColumnMappings.Add("ID_AKSESORE", "ID_AKSESORE");
            tableMapping.ColumnMappings.Add("FORMULA", "FORMULA");
            this._adapter.TableMappings.Add(tableMapping);
            this._adapter.DeleteCommand = new System.Data.OleDb.OleDbCommand();
            this._adapter.DeleteCommand.Connection = this.Connection;
            this._adapter.DeleteCommand.CommandText = @"DELETE FROM `PRODUKT_AKSESORE` WHERE ((`ID_PRODUKT_AKSESORE` = ?) AND ((? = 1 AND `ID_PRODUKTI` IS NULL) OR (`ID_PRODUKTI` = ?)) AND ((? = 1 AND `ID_AKSESORE_ALUMINI` IS NULL) OR (`ID_AKSESORE_ALUMINI` = ?)) AND ((? = 1 AND `ID_AKSESORE_XHAMI` IS NULL) OR (`ID_AKSESORE_XHAMI` = ?)) AND ((? = 1 AND `ID_AKSESORE` IS NULL) OR (`ID_AKSESORE` = ?)) AND ((? = 1 AND `FORMULA` IS NULL) OR (`FORMULA` = ?)))";
            this._adapter.DeleteCommand.CommandType = System.Data.CommandType.Text;
            this._adapter.DeleteCommand.Parameters.Add(new System.Data.OleDb.OleDbParameter("Original_ID_PRODUKT_AKSESORE", System.Data.OleDb.OleDbType.Integer, 0, System.Data.ParameterDirection.Input, ((byte)(0)), ((byte)(0)), "ID_PRODUKT_AKSESORE", System.Data.DataRowVersion.Original, false, null));
            this._adapter.DeleteCommand.Parameters.Add(new System.Data.OleDb.OleDbParameter("IsNull_ID_PRODUKTI", System.Data.OleDb.OleDbType.Integer, 0, System.Data.ParameterDirection.Input, ((byte)(0)), ((byte)(0)), "ID_PRODUKTI", System.Data.DataRowVersion.Original, true, null));
            this._adapter.DeleteCommand.Parameters.Add(new System.Data.OleDb.OleDbParameter("Original_ID_PRODUKTI", System.Data.OleDb.OleDbType.Integer, 0, System.Data.ParameterDirection.Input, ((byte)(0)), ((byte)(0)), "ID_PRODUKTI", System.Data.DataRowVersion.Original, false, null));
            this._adapter.DeleteCommand.Parameters.Add(new System.Data.OleDb.OleDbParameter("IsNull_ID_AKSESORE_ALUMINI", System.Data.OleDb.OleDbType.Integer, 0, System.Data.ParameterDirection.Input, ((byte)(0)), ((byte)(0)), "ID_AKSESORE_ALUMINI", System.Data.DataRowVersion.Original, true, null));
            this._adapter.DeleteCommand.Parameters.Add(new System.Data.OleDb.OleDbParameter("Original_ID_AKSESORE_ALUMINI", System.Data.OleDb.OleDbType.Integer, 0, System.Data.ParameterDirection.Input, ((byte)(0)), ((byte)(0)), "ID_AKSESORE_ALUMINI", System.Data.DataRowVersion.Original, false, null));
            this._adapter.DeleteCommand.Parameters.Add(new System.Data.OleDb.OleDbParameter("IsNull_ID_AKSESORE_XHAMI", System.Data.OleDb.OleDbType.Integer, 0, System.Data.ParameterDirection.Input, ((byte)(0)), ((byte)(0)), "ID_AKSESORE_XHAMI", System.Data.DataRowVersion.Original, true, null));
            this._adapter.DeleteCommand.Parameters.Add(new System.Data.OleDb.OleDbParameter("Original_ID_AKSESORE_XHAMI", System.Data.OleDb.OleDbType.Integer, 0, System.Data.ParameterDirection.Input, ((byte)(0)), ((byte)(0)), "ID_AKSESORE_XHAMI", System.Data.DataRowVersion.Original, false, null));
            this._adapter.DeleteCommand.Parameters.Add(new System.Data.OleDb.OleDbParameter("IsNull_ID_AKSESORE", System.Data.OleDb.OleDbType.Integer, 0, System.Data.ParameterDirection.Input, ((byte)(0)), ((byte)(0)), "ID_AKSESORE", System.Data.DataRowVersion.Original, true, null));
            this._adapter.DeleteCommand.Parameters.Add(new System.Data.OleDb.OleDbParameter("Original_ID_AKSESORE", System.Data.OleDb.OleDbType.Integer, 0, System.Data.ParameterDirection.Input, ((byte)(0)), ((byte)(0)), "ID_AKSESORE", System.Data.DataRowVersion.Original, false, null));
            this._adapter.DeleteCommand.Parameters.Add(new System.Data.OleDb.OleDbParameter("IsNull_FORMULA", System.Data.OleDb.OleDbType.Integer, 0, System.Data.ParameterDirection.Input, ((byte)(0)), ((byte)(0)), "FORMULA", System.Data.DataRowVersion.Original, true, null));
            this._adapter.DeleteCommand.Parameters.Add(new System.Data.OleDb.OleDbParameter("Original_FORMULA", System.Data.OleDb.OleDbType.VarWChar, 0, System.Data.ParameterDirection.Input, ((byte)(0)), ((byte)(0)), "FORMULA", System.Data.DataRowVersion.Original, false, null));
            this._adapter.InsertCommand = new System.Data.OleDb.OleDbCommand();
            this._adapter.InsertCommand.Connection = this.Connection;
            this._adapter.InsertCommand.CommandText = "INSERT INTO `PRODUKT_AKSESORE` (`ID_PRODUKTI`, `ID_AKSESORE_ALUMINI`, `ID_AKSESOR" +
                "E_XHAMI`, `ID_AKSESORE`, `FORMULA`) VALUES (?, ?, ?, ?, ?)";
            this._adapter.InsertCommand.CommandType = System.Data.CommandType.Text;
            this._adapter.InsertCommand.Parameters.Add(new System.Data.OleDb.OleDbParameter("ID_PRODUKTI", System.Data.OleDb.OleDbType.Integer, 0, System.Data.ParameterDirection.Input, ((byte)(0)), ((byte)(0)), "ID_PRODUKTI", System.Data.DataRowVersion.Current, false, null));
            this._adapter.InsertCommand.Parameters.Add(new System.Data.OleDb.OleDbParameter("ID_AKSESORE_ALUMINI", System.Data.OleDb.OleDbType.Integer, 0, System.Data.ParameterDirection.Input, ((byte)(0)), ((byte)(0)), "ID_AKSESORE_ALUMINI", System.Data.DataRowVersion.Current, false, null));
            this._adapter.InsertCommand.Parameters.Add(new System.Data.OleDb.OleDbParameter("ID_AKSESORE_XHAMI", System.Data.OleDb.OleDbType.Integer, 0, System.Data.ParameterDirection.Input, ((byte)(0)), ((byte)(0)), "ID_AKSESORE_XHAMI", System.Data.DataRowVersion.Current, false, null));
            this._adapter.InsertCommand.Parameters.Add(new System.Data.OleDb.OleDbParameter("ID_AKSESORE", System.Data.OleDb.OleDbType.Integer, 0, System.Data.ParameterDirection.Input, ((byte)(0)), ((byte)(0)), "ID_AKSESORE", System.Data.DataRowVersion.Current, false, null));
            this._adapter.InsertCommand.Parameters.Add(new System.Data.OleDb.OleDbParameter("FORMULA", System.Data.OleDb.OleDbType.VarWChar, 0, System.Data.ParameterDirection.Input, ((byte)(0)), ((byte)(0)), "FORMULA", System.Data.DataRowVersion.Current, false, null));
            this._adapter.UpdateCommand = new System.Data.OleDb.OleDbCommand();
            this._adapter.UpdateCommand.Connection = this.Connection;
            this._adapter.UpdateCommand.CommandText = @"UPDATE `PRODUKT_AKSESORE` SET `ID_PRODUKTI` = ?, `ID_AKSESORE_ALUMINI` = ?, `ID_AKSESORE_XHAMI` = ?, `ID_AKSESORE` = ?, `FORMULA` = ? WHERE ((`ID_PRODUKT_AKSESORE` = ?) AND ((? = 1 AND `ID_PRODUKTI` IS NULL) OR (`ID_PRODUKTI` = ?)) AND ((? = 1 AND `ID_AKSESORE_ALUMINI` IS NULL) OR (`ID_AKSESORE_ALUMINI` = ?)) AND ((? = 1 AND `ID_AKSESORE_XHAMI` IS NULL) OR (`ID_AKSESORE_XHAMI` = ?)) AND ((? = 1 AND `ID_AKSESORE` IS NULL) OR (`ID_AKSESORE` = ?)) AND ((? = 1 AND `FORMULA` IS NULL) OR (`FORMULA` = ?)))";
            this._adapter.UpdateCommand.CommandType = System.Data.CommandType.Text;
            this._adapter.UpdateCommand.Parameters.Add(new System.Data.OleDb.OleDbParameter("ID_PRODUKTI", System.Data.OleDb.OleDbType.Integer, 0, System.Data.ParameterDirection.Input, ((byte)(0)), ((byte)(0)), "ID_PRODUKTI", System.Data.DataRowVersion.Current, false, null));
            this._adapter.UpdateCommand.Parameters.Add(new System.Data.OleDb.OleDbParameter("ID_AKSESORE_ALUMINI", System.Data.OleDb.OleDbType.Integer, 0, System.Data.ParameterDirection.Input, ((byte)(0)), ((byte)(0)), "ID_AKSESORE_ALUMINI", System.Data.DataRowVersion.Current, false, null));
            this._adapter.UpdateCommand.Parameters.Add(new System.Data.OleDb.OleDbParameter("ID_AKSESORE_XHAMI", System.Data.OleDb.OleDbType.Integer, 0, System.Data.ParameterDirection.Input, ((byte)(0)), ((byte)(0)), "ID_AKSESORE_XHAMI", System.Data.DataRowVersion.Current, false, null));
            this._adapter.UpdateCommand.Parameters.Add(new System.Data.OleDb.OleDbParameter("ID_AKSESORE", System.Data.OleDb.OleDbType.Integer, 0, System.Data.ParameterDirection.Input, ((byte)(0)), ((byte)(0)), "ID_AKSESORE", System.Data.DataRowVersion.Current, false, null));
            this._adapter.UpdateCommand.Parameters.Add(new System.Data.OleDb.OleDbParameter("FORMULA", System.Data.OleDb.OleDbType.VarWChar, 0, System.Data.ParameterDirection.Input, ((byte)(0)), ((byte)(0)), "FORMULA", System.Data.DataRowVersion.Current, false, null));
            this._adapter.UpdateCommand.Parameters.Add(new System.Data.OleDb.OleDbParameter("Original_ID_PRODUKT_AKSESORE", System.Data.OleDb.OleDbType.Integer, 0, System.Data.ParameterDirection.Input, ((byte)(0)), ((byte)(0)), "ID_PRODUKT_AKSESORE", System.Data.DataRowVersion.Original, false, null));
            this._adapter.UpdateCommand.Parameters.Add(new System.Data.OleDb.OleDbParameter("IsNull_ID_PRODUKTI", System.Data.OleDb.OleDbType.Integer, 0, System.Data.ParameterDirection.Input, ((byte)(0)), ((byte)(0)), "ID_PRODUKTI", System.Data.DataRowVersion.Original, true, null));
            this._adapter.UpdateCommand.Parameters.Add(new System.Data.OleDb.OleDbParameter("Original_ID_PRODUKTI", System.Data.OleDb.OleDbType.Integer, 0, System.Data.ParameterDirection.Input, ((byte)(0)), ((byte)(0)), "ID_PRODUKTI", System.Data.DataRowVersion.Original, false, null));
            this._adapter.UpdateCommand.Parameters.Add(new System.Data.OleDb.OleDbParameter("IsNull_ID_AKSESORE_ALUMINI", System.Data.OleDb.OleDbType.Integer, 0, System.Data.ParameterDirection.Input, ((byte)(0)), ((byte)(0)), "ID_AKSESORE_ALUMINI", System.Data.DataRowVersion.Original, true, null));
            this._adapter.UpdateCommand.Parameters.Add(new System.Data.OleDb.OleDbParameter("Original_ID_AKSESORE_ALUMINI", System.Data.OleDb.OleDbType.Integer, 0, System.Data.ParameterDirection.Input, ((byte)(0)), ((byte)(0)), "ID_AKSESORE_ALUMINI", System.Data.DataRowVersion.Original, false, null));
            this._adapter.UpdateCommand.Parameters.Add(new System.Data.OleDb.OleDbParameter("IsNull_ID_AKSESORE_XHAMI", System.Data.OleDb.OleDbType.Integer, 0, System.Data.ParameterDirection.Input, ((byte)(0)), ((byte)(0)), "ID_AKSESORE_XHAMI", System.Data.DataRowVersion.Original, true, null));
            this._adapter.UpdateCommand.Parameters.Add(new System.Data.OleDb.OleDbParameter("Original_ID_AKSESORE_XHAMI", System.Data.OleDb.OleDbType.Integer, 0, System.Data.ParameterDirection.Input, ((byte)(0)), ((byte)(0)), "ID_AKSESORE_XHAMI", System.Data.DataRowVersion.Original, false, null));
            this._adapter.UpdateCommand.Parameters.Add(new System.Data.OleDb.OleDbParameter("IsNull_ID_AKSESORE", System.Data.OleDb.OleDbType.Integer, 0, System.Data.ParameterDirection.Input, ((byte)(0)), ((byte)(0)), "ID_AKSESORE", System.Data.DataRowVersion.Original, true, null));
            this._adapter.UpdateCommand.Parameters.Add(new System.Data.OleDb.OleDbParameter("Original_ID_AKSESORE", System.Data.OleDb.OleDbType.Integer, 0, System.Data.ParameterDirection.Input, ((byte)(0)), ((byte)(0)), "ID_AKSESORE", System.Data.DataRowVersion.Original, false, null));
            this._adapter.UpdateCommand.Parameters.Add(new System.Data.OleDb.OleDbParameter("IsNull_FORMULA", System.Data.OleDb.OleDbType.Integer, 0, System.Data.ParameterDirection.Input, ((byte)(0)), ((byte)(0)), "FORMULA", System.Data.DataRowVersion.Original, true, null));
            this._adapter.UpdateCommand.Parameters.Add(new System.Data.OleDb.OleDbParameter("Original_FORMULA", System.Data.OleDb.OleDbType.VarWChar, 0, System.Data.ParameterDirection.Input, ((byte)(0)), ((byte)(0)), "FORMULA", System.Data.DataRowVersion.Original, false, null));
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitConnection() {
            this._connection = new System.Data.OleDb.OleDbConnection();
            this._connection.ConnectionString = global::PespaSistem.Properties.Settings.Default.PespaSistemConnectionString;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitCommandCollection() {
            this._commandCollection = new System.Data.OleDb.OleDbCommand[2];
            this._commandCollection[0] = new System.Data.OleDb.OleDbCommand();
            this._commandCollection[0].Connection = this.Connection;
            this._commandCollection[0].CommandText = "SELECT     ID_PRODUKT_AKSESORE, ID_PRODUKTI, ID_AKSESORE_ALUMINI, ID_AKSESORE_XHA" +
                "MI, ID_AKSESORE, FORMULA\r\nFROM         PRODUKT_AKSESORE";
            this._commandCollection[0].CommandType = System.Data.CommandType.Text;
            this._commandCollection[1] = new System.Data.OleDb.OleDbCommand();
            this._commandCollection[1].Connection = this.Connection;
            this._commandCollection[1].CommandText = "SELECT     ID_PRODUKT_AKSESORE, ID_PRODUKTI, ID_AKSESORE_ALUMINI, ID_AKSESORE_XHA" +
                "MI, ID_AKSESORE, FORMULA\r\nFROM         PRODUKT_AKSESORE\r\nWHERE     (ID_PRODUKTI " +
                "= ?)";
            this._commandCollection[1].CommandType = System.Data.CommandType.Text;
            this._commandCollection[1].Parameters.Add(new System.Data.OleDb.OleDbParameter("ID_PRODUKTI", System.Data.OleDb.OleDbType.Integer, 0, System.Data.ParameterDirection.Input, ((byte)(0)), ((byte)(0)), "ID_PRODUKTI", System.Data.DataRowVersion.Current, false, null));
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")]
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Fill, true)]
        public virtual int Fill(DsProdukteTotal.PRODUKT_AKSESOREDataTable dataTable) {
            this.Adapter.SelectCommand = this.CommandCollection[0];
            if ((this.ClearBeforeFill == true)) {
                dataTable.Clear();
            }
            int returnValue = this.Adapter.Fill(dataTable);
            return returnValue;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")]
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Select, true)]
        public virtual DsProdukteTotal.PRODUKT_AKSESOREDataTable GetData() {
            this.Adapter.SelectCommand = this.CommandCollection[0];
            DsProdukteTotal.PRODUKT_AKSESOREDataTable dataTable = new DsProdukteTotal.PRODUKT_AKSESOREDataTable();
            this.Adapter.Fill(dataTable);
            return dataTable;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")]
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Fill, false)]
        public virtual int FillByIdProdukti(DsProdukteTotal.PRODUKT_AKSESOREDataTable dataTable, System.Nullable<int> ID_PRODUKTI) {
            this.Adapter.SelectCommand = this.CommandCollection[1];
            if ((ID_PRODUKTI.HasValue == true)) {
                this.Adapter.SelectCommand.Parameters[0].Value = ((int)(ID_PRODUKTI.Value));
            }
            else {
                this.Adapter.SelectCommand.Parameters[0].Value = System.DBNull.Value;
            }
            if ((this.ClearBeforeFill == true)) {
                dataTable.Clear();
            }
            int returnValue = this.Adapter.Fill(dataTable);
            return returnValue;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")]
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Select, false)]
        public virtual DsProdukteTotal.PRODUKT_AKSESOREDataTable GetDataByIdProdukti(System.Nullable<int> ID_PRODUKTI) {
            this.Adapter.SelectCommand = this.CommandCollection[1];
            if ((ID_PRODUKTI.HasValue == true)) {
                this.Adapter.SelectCommand.Parameters[0].Value = ((int)(ID_PRODUKTI.Value));
            }
            else {
                this.Adapter.SelectCommand.Parameters[0].Value = System.DBNull.Value;
            }
            DsProdukteTotal.PRODUKT_AKSESOREDataTable dataTable = new DsProdukteTotal.PRODUKT_AKSESOREDataTable();
            this.Adapter.Fill(dataTable);
            return dataTable;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")]
        public virtual int Update(DsProdukteTotal.PRODUKT_AKSESOREDataTable dataTable) {
            return this.Adapter.Update(dataTable);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")]
        public virtual int Update(DsProdukteTotal dataSet) {
            return this.Adapter.Update(dataSet, "PRODUKT_AKSESORE");
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")]
        public virtual int Update(System.Data.DataRow dataRow) {
            return this.Adapter.Update(new System.Data.DataRow[] {
                        dataRow});
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")]
        public virtual int Update(System.Data.DataRow[] dataRows) {
            return this.Adapter.Update(dataRows);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")]
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Delete, true)]
        public virtual int Delete(int Original_ID_PRODUKT_AKSESORE, System.Nullable<int> Original_ID_PRODUKTI, System.Nullable<int> Original_ID_AKSESORE_ALUMINI, System.Nullable<int> Original_ID_AKSESORE_XHAMI, System.Nullable<int> Original_ID_AKSESORE, string Original_FORMULA) {
            this.Adapter.DeleteCommand.Parameters[0].Value = ((int)(Original_ID_PRODUKT_AKSESORE));
            if ((Original_ID_PRODUKTI.HasValue == true)) {
                this.Adapter.DeleteCommand.Parameters[1].Value = ((object)(0));
                this.Adapter.DeleteCommand.Parameters[2].Value = ((int)(Original_ID_PRODUKTI.Value));
            }
            else {
                this.Adapter.DeleteCommand.Parameters[1].Value = ((object)(1));
                this.Adapter.DeleteCommand.Parameters[2].Value = System.DBNull.Value;
            }
            if ((Original_ID_AKSESORE_ALUMINI.HasValue == true)) {
                this.Adapter.DeleteCommand.Parameters[3].Value = ((object)(0));
                this.Adapter.DeleteCommand.Parameters[4].Value = ((int)(Original_ID_AKSESORE_ALUMINI.Value));
            }
            else {
                this.Adapter.DeleteCommand.Parameters[3].Value = ((object)(1));
                this.Adapter.DeleteCommand.Parameters[4].Value = System.DBNull.Value;
            }
            if ((Original_ID_AKSESORE_XHAMI.HasValue == true)) {
                this.Adapter.DeleteCommand.Parameters[5].Value = ((object)(0));
                this.Adapter.DeleteCommand.Parameters[6].Value = ((int)(Original_ID_AKSESORE_XHAMI.Value));
            }
            else {
                this.Adapter.DeleteCommand.Parameters[5].Value = ((object)(1));
                this.Adapter.DeleteCommand.Parameters[6].Value = System.DBNull.Value;
            }
            if ((Original_ID_AKSESORE.HasValue == true)) {
                this.Adapter.DeleteCommand.Parameters[7].Value = ((object)(0));
                this.Adapter.DeleteCommand.Parameters[8].Value = ((int)(Original_ID_AKSESORE.Value));
            }
            else {
                this.Adapter.DeleteCommand.Parameters[7].Value = ((object)(1));
                this.Adapter.DeleteCommand.Parameters[8].Value = System.DBNull.Value;
            }
            if ((Original_FORMULA == null)) {
                this.Adapter.DeleteCommand.Parameters[9].Value = ((object)(1));
                this.Adapter.DeleteCommand.Parameters[10].Value = System.DBNull.Value;
            }
            else {
                this.Adapter.DeleteCommand.Parameters[9].Value = ((object)(0));
                this.Adapter.DeleteCommand.Parameters[10].Value = ((string)(Original_FORMULA));
            }
            System.Data.ConnectionState previousConnectionState = this.Adapter.DeleteCommand.Connection.State;
            if (((this.Adapter.DeleteCommand.Connection.State & System.Data.ConnectionState.Open) 
                        != System.Data.ConnectionState.Open)) {
                this.Adapter.DeleteCommand.Connection.Open();
            }
            try {
                int returnValue = this.Adapter.DeleteCommand.ExecuteNonQuery();
                return returnValue;
            }
            finally {
                if ((previousConnectionState == System.Data.ConnectionState.Closed)) {
                    this.Adapter.DeleteCommand.Connection.Close();
                }
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")]
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Insert, true)]
        public virtual int Insert(System.Nullable<int> ID_PRODUKTI, System.Nullable<int> ID_AKSESORE_ALUMINI, System.Nullable<int> ID_AKSESORE_XHAMI, System.Nullable<int> ID_AKSESORE, string FORMULA) {
            if ((ID_PRODUKTI.HasValue == true)) {
                this.Adapter.InsertCommand.Parameters[0].Value = ((int)(ID_PRODUKTI.Value));
            }
            else {
                this.Adapter.InsertCommand.Parameters[0].Value = System.DBNull.Value;
            }
            if ((ID_AKSESORE_ALUMINI.HasValue == true)) {
                this.Adapter.InsertCommand.Parameters[1].Value = ((int)(ID_AKSESORE_ALUMINI.Value));
            }
            else {
                this.Adapter.InsertCommand.Parameters[1].Value = System.DBNull.Value;
            }
            if ((ID_AKSESORE_XHAMI.HasValue == true)) {
                this.Adapter.InsertCommand.Parameters[2].Value = ((int)(ID_AKSESORE_XHAMI.Value));
            }
            else {
                this.Adapter.InsertCommand.Parameters[2].Value = System.DBNull.Value;
            }
            if ((ID_AKSESORE.HasValue == true)) {
                this.Adapter.InsertCommand.Parameters[3].Value = ((int)(ID_AKSESORE.Value));
            }
            else {
                this.Adapter.InsertCommand.Parameters[3].Value = System.DBNull.Value;
            }
            if ((FORMULA == null)) {
                this.Adapter.InsertCommand.Parameters[4].Value = System.DBNull.Value;
            }
            else {
                this.Adapter.InsertCommand.Parameters[4].Value = ((string)(FORMULA));
            }
            System.Data.ConnectionState previousConnectionState = this.Adapter.InsertCommand.Connection.State;
            if (((this.Adapter.InsertCommand.Connection.State & System.Data.ConnectionState.Open) 
                        != System.Data.ConnectionState.Open)) {
                this.Adapter.InsertCommand.Connection.Open();
            }
            try {
                int returnValue = this.Adapter.InsertCommand.ExecuteNonQuery();
                return returnValue;
            }
            finally {
                if ((previousConnectionState == System.Data.ConnectionState.Closed)) {
                    this.Adapter.InsertCommand.Connection.Close();
                }
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")]
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Update, true)]
        public virtual int Update(System.Nullable<int> ID_PRODUKTI, System.Nullable<int> ID_AKSESORE_ALUMINI, System.Nullable<int> ID_AKSESORE_XHAMI, System.Nullable<int> ID_AKSESORE, string FORMULA, int Original_ID_PRODUKT_AKSESORE, System.Nullable<int> Original_ID_PRODUKTI, System.Nullable<int> Original_ID_AKSESORE_ALUMINI, System.Nullable<int> Original_ID_AKSESORE_XHAMI, System.Nullable<int> Original_ID_AKSESORE, string Original_FORMULA) {
            if ((ID_PRODUKTI.HasValue == true)) {
                this.Adapter.UpdateCommand.Parameters[0].Value = ((int)(ID_PRODUKTI.Value));
            }
            else {
                this.Adapter.UpdateCommand.Parameters[0].Value = System.DBNull.Value;
            }
            if ((ID_AKSESORE_ALUMINI.HasValue == true)) {
                this.Adapter.UpdateCommand.Parameters[1].Value = ((int)(ID_AKSESORE_ALUMINI.Value));
            }
            else {
                this.Adapter.UpdateCommand.Parameters[1].Value = System.DBNull.Value;
            }
            if ((ID_AKSESORE_XHAMI.HasValue == true)) {
                this.Adapter.UpdateCommand.Parameters[2].Value = ((int)(ID_AKSESORE_XHAMI.Value));
            }
            else {
                this.Adapter.UpdateCommand.Parameters[2].Value = System.DBNull.Value;
            }
            if ((ID_AKSESORE.HasValue == true)) {
                this.Adapter.UpdateCommand.Parameters[3].Value = ((int)(ID_AKSESORE.Value));
            }
            else {
                this.Adapter.UpdateCommand.Parameters[3].Value = System.DBNull.Value;
            }
            if ((FORMULA == null)) {
                this.Adapter.UpdateCommand.Parameters[4].Value = System.DBNull.Value;
            }
            else {
                this.Adapter.UpdateCommand.Parameters[4].Value = ((string)(FORMULA));
            }
            this.Adapter.UpdateCommand.Parameters[5].Value = ((int)(Original_ID_PRODUKT_AKSESORE));
            if ((Original_ID_PRODUKTI.HasValue == true)) {
                this.Adapter.UpdateCommand.Parameters[6].Value = ((object)(0));
                this.Adapter.UpdateCommand.Parameters[7].Value = ((int)(Original_ID_PRODUKTI.Value));
            }
            else {
                this.Adapter.UpdateCommand.Parameters[6].Value = ((object)(1));
                this.Adapter.UpdateCommand.Parameters[7].Value = System.DBNull.Value;
            }
            if ((Original_ID_AKSESORE_ALUMINI.HasValue == true)) {
                this.Adapter.UpdateCommand.Parameters[8].Value = ((object)(0));
                this.Adapter.UpdateCommand.Parameters[9].Value = ((int)(Original_ID_AKSESORE_ALUMINI.Value));
            }
            else {
                this.Adapter.UpdateCommand.Parameters[8].Value = ((object)(1));
                this.Adapter.UpdateCommand.Parameters[9].Value = System.DBNull.Value;
            }
            if ((Original_ID_AKSESORE_XHAMI.HasValue == true)) {
                this.Adapter.UpdateCommand.Parameters[10].Value = ((object)(0));
                this.Adapter.UpdateCommand.Parameters[11].Value = ((int)(Original_ID_AKSESORE_XHAMI.Value));
            }
            else {
                this.Adapter.UpdateCommand.Parameters[10].Value = ((object)(1));
                this.Adapter.UpdateCommand.Parameters[11].Value = System.DBNull.Value;
            }
            if ((Original_ID_AKSESORE.HasValue == true)) {
                this.Adapter.UpdateCommand.Parameters[12].Value = ((object)(0));
                this.Adapter.UpdateCommand.Parameters[13].Value = ((int)(Original_ID_AKSESORE.Value));
            }
            else {
                this.Adapter.UpdateCommand.Parameters[12].Value = ((object)(1));
                this.Adapter.UpdateCommand.Parameters[13].Value = System.DBNull.Value;
            }
            if ((Original_FORMULA == null)) {
                this.Adapter.UpdateCommand.Parameters[14].Value = ((object)(1));
                this.Adapter.UpdateCommand.Parameters[15].Value = System.DBNull.Value;
            }
            else {
                this.Adapter.UpdateCommand.Parameters[14].Value = ((object)(0));
                this.Adapter.UpdateCommand.Parameters[15].Value = ((string)(Original_FORMULA));
            }
            System.Data.ConnectionState previousConnectionState = this.Adapter.UpdateCommand.Connection.State;
            if (((this.Adapter.UpdateCommand.Connection.State & System.Data.ConnectionState.Open) 
                        != System.Data.ConnectionState.Open)) {
                this.Adapter.UpdateCommand.Connection.Open();
            }
            try {
                int returnValue = this.Adapter.UpdateCommand.ExecuteNonQuery();
                return returnValue;
            }
            finally {
                if ((previousConnectionState == System.Data.ConnectionState.Closed)) {
                    this.Adapter.UpdateCommand.Connection.Close();
                }
            }
        }
    }
}

#pragma warning restore 1591